### ISSUE TITLE
Wow

### ISSUE THREAD

**Issue by MartijnR** [alxndrsn/enketo-client-side-transformer#1]
I didn't expect those sheets would run in browsers! I think I last tried a few years ago. Maybe XSL is not entirely dead?

This could be very exciting to use for a hybrid mobile client if we can rely on the (equality of the) output amongst all the different webviews.

**Comment by alxndrsn** [comment]
:-)

XSL may be dead - the Chrome team don't seem keen, for sure - I guess you've read stuff like:

> We would prefer to remove support for XSLT, but we haven't decided whether we're actually going to remove the feature.  If you're using XSLT on the client, I'd recommend migrating to HTML, CSS, and JavaScript, perhaps by applying the XSLT on the server.  If/when we decide to remove XSLT support, we'll communicate more broadly about the timeline and migration options.
> 
> &mdash; _<cite>https://code.google.com/p/chromium/issues/detail?id=8441</cite>_

Also there are still some unresolved issues with unsupported EXSLT/XSLT 2.0 tags used in the enketo `.xsl` files, specifically:
- `<str:replace/>`
- `<dyn:evaluate/>`
- `<str:tokenize/>`

There are issues filed at https://github.com/alxndrsn/openrosa-xpath-evaluator/issues, but they should be in this project - I'll shift them over.

**Comment by alxndrsn** [comment]
Also worth noting that I haven't considered IE support...

**Comment by MartijnR** [comment]
Oh I see. Yes, that's why I was surprised. I thought EXSLT wouldn't work properly in the browser.

Gee that openrosa-xpath-evaluator looks brilliant!  That approach should be much faster. I'm still trying to wrap my head around it. I've read somewhere that Edge (the new IE) might get a native XPath evaluator too.
