### ISSUE TITLE
Make this a fork of enketo-xslt

### ISSUE THREAD

**Issue by alxndrsn** [alxndrsn/enketo-client-side-transformer#13]
It's not clear why this project is not a fork of `enketo/enketo-xslt`.

**Comment by MartijnR** [comment]
Yes, I was wondering if enketo-xslt could be added as an npm module, or if you had to make changes to the sheets.

**Comment by alxndrsn** [comment]
Sheets have some tweaks, but they aren't extensive.  Mostly to work around XSLT 2.0 stuff, and browser inconsistencies.
